/* #ifndef _VOICE_H_
#define _VOICE_H_
#define DEF_VoiceSegmentEndFlag 0xFA
enum {
VOICE_Alarm,
VOICE_OPEN,
VOICE_CLOSE,
VOICE_PLEASE,
VOICE_INPUT,
VOICE_FINGERPRINT,
VOICE_PASSWORD,
VOICE_OR,
VOICE_AGAIN,
VOICE_REGISTER,
VOICE_SUCCESS,
VOICE_FAIL,
VOICE_RESTORE_FACTORY,
VOICE_IDENTIFY,
VOICE_PASSED,
VOICE_VOLTAGE_LOW,
VOICE_REPLACE_BATTERY,
VOICE_SAFE,
VOICE_MODE,
VOICE_RENEW,
VOICE_HARDWARE,
VOICE_SOFTWARE,
VOICE_VERSION,
VOICE_POINT,
VOICE_ZERO,
VOICE_ONE,
VOICE_TWO,
VOICE_THREE,
VOICE_FOUR,
VOICE_FIVE,
VOICE_SIX,
VOICE_SEVEN,
VOICE_EIGHT,
VOICE_NINE,
VOICE_PRESS,
VOICE_PRESS_POUND,
VOICE_PRESS_ASTER,
VOICE_ORDINARY,
VOICE_ADMINISTRATOR,
VOICE_USER,
VOICE_REPEAT,
VOICE_USER_IS_FULL,
VOICE_IDENTIFY_ADMINISTRATOR,
VOICE_PLEASE_TRY_AGAIN,
VOICE_RETURN_PRE_MENU,
VOICE_EXIT_MENU,
VOICE_PORTABLE_MODE,
VOICE_NUMBER,
VOICE_SYS_LOCKED,
VOICE_SYSTEM,
VOICE_WATER_DROP,
VOICE_BEEP,
VOICE_ALARM1,
VOICE_ALARM2,
VOICE_FAIL_SOUND,
};
void PlayWaterDrop(void);
void PlayPleaseInputAain(void);
void PlayPleaseRenewInput(void);
void PlayPleaseInputFpm(void);
void PlayRegisterFail(void);
void PlayAlarmOpened(void);
void PlayPleaseInputPassword(void);
#endif
 */